### ISSUE TITLE
Sometimes submitting a claim is "stuck" at multiple images upload

### ISSUE THREAD

**Issue by excieve** [badparking/badparking-android#99]
Sometimes when submitting a claim with several images, the process seems stuck at an image upload dialogue (e.g "Uploading photo 1/2"). At the same time all images are successfully uploaded to the server and claim is completely available.

IMO this happens due to asynchronous nature of network calls so that image "1" may be actually uploaded after image "2". Since counter is used in a condition to check that all images were uploaded to proceed with the flow, this can easily cause the "done" dialogue to be shown before the "uploaded image 1" dialogue and be overlapped.

Refer to this:
https://github.com/badparking/badparking-android/blob/develop/app/src/main/java/ua/in/badparking/ui/fragments/ClaimOverviewFragment.java#L283
https://github.com/badparking/badparking-android/blob/develop/app/src/main/java/ua/in/badparking/ui/fragments/ClaimOverviewFragment.java#L247

**Comment by dima-ko** [comment]
@renka can you make uploading of photo's sequential, not in parallel?

**Comment by excieve** [comment]
As an alternative you could drop the counter and use some kind of a map between file and upload status. Then check completeness based on all map values being "true". This would allow to keep the upload parallel.

**Comment by dima-ko** [comment]
@excieve yeah, but will it be faster in parallel? I think phone's 3G connection is bottle neck anyway?

**Comment by excieve** [comment]
Depends on file size and current bandwidth. In the worst case it's about the same as sequential. In the best case... let's say 2Mbps can completely upload two 125K files in a second. So really it depends on how much we're compressing the files.

**Comment by dima-ko** [comment]
ok, I see, then counter/map is the way to go. Can you add that @renka ?

**Comment by renka** [comment]
Yes
